In [1]:
num=5
type(num)

int

In [2]:
a=bool(num)
b=True
n=int(b)
c="Hola"

In [3]:
c[0]

'H'

In [4]:
c[:2]

'Ho'

In [5]:
c[2:]

'la'

In [6]:
c[1:3]

'ol'

In [7]:
len(c)

4

In [9]:
min(c)

'H'

In [10]:
max(c)

'o'

In [12]:
n1=4
n2=6
n=n1+n2
n

10

In [13]:
c*3

'HolaHolaHola'

In [15]:
print(c)

Hola


1. Introduce tu nombre y después muestra un mensaje personalizado (Ej Hola Juan, bienvenido al curso de Big Data, donde Juan será el nombre introducido).

2. Escribe una cadena. Muestra los caracteres que ocupan posiciones pares.

3. Escribe una cadena y muéstrala al revés.

4. Escribe una cadena y dos valores enteros. El primer número será la primera posición y el segundo será la segunda. Muestra la subcaden comprendida entre las dos posiciones (ambas incluidas).

In [17]:
#1
Nombre="Sandra"
mensaje="Hola "+ Nombre +", bienvenido al curso de Big Data..."
print(mensaje)

Hola Sandra, bienvenido al curso de Big Data...


In [20]:
#2
cad="jgrijhir jijrpo"
indices=cad[::3]
# cad [inicio:fin:salto]
print(indices)

jiijr


In [22]:
#3
cad="Hola mundo"
print(cad[::-2])

onmao


In [24]:
#4
a=3
b=6
print(cad[a:b])

a m


In [25]:
"""
instrucciones 1
if condición:
    instrucciones 2
elif condición 2:
    instrucciones 3
else:
    instruciones 4
instrucciones 5
"""

import random
a=random.randint(0, 100)
if a<10:
    print("El número es menor que 10")
elif a<50:
    print("El número es menor que 50")
else:
    print("El número se encuentra entres 50 y 100")
print(a)

El número es menor que 50
10


In [38]:
"""
instrucciones 1
for variable in secuencia:
    instrucciones 2
instrucciones 3
"""

for i in range(1,10,2):
    print(i)


1
3
5
7
9


In [27]:
"""
instrucciones 1
while condición:
    instrucciones 2
instrucciones 3
"""
i=0
while i<10:
    print(i)
    i=i+1

0
1
2
3
4
5
6
7
8
9


1. Escribir una edad y decir si es mayor de edad o no.
2. Escribir un número e indicar si es par.
3. Escribir dos números y si el primero es mayor que el segundo, intercambiarlos.
4. Escribe un número entero positivo y muestra la tabla de multiplicar.
5. Escribe una lista de 10 números e indica cuántos negativos, positivos y ceros se han introducidos.

In [32]:
a=5
b=20
print(f"Número de manzanas: {a}")

Número de manzanas: 5


In [33]:
#1. Escribir una edad y decir si es mayor de edad o no.
edad=20
if edad<18:
    print("Menor de edad")
else: 
     print("Mayor de edad")

Mayor de edad


In [34]:
#2. Escribir un número e indicar si es par.
num=4
if num%2==0:
    print("Par")
else:
    print("Impar")

Par


In [35]:
#3. Escribir dos números y si el primero es mayor que el segundo, intercambiarlos.
a=4
b=2
if a>b:
    aux=a
    a=b
    b=aux
print(a,b)

2 4


In [37]:
# Escribe un número entero positivo y muestra la tabla de multiplicar.
num=4
for i in range(1,11):
    print(4*i)

4
8
12
16
20
24
28
32
36
40


In [40]:
# Escribe una lista de 10 números e indica cuántos negativos, positivos y ceros se han introducidos.
neg=0
pos=0
ceros=0
lista=[3,7,5,2,1,3,0,0,4]
for i in lista:
    if i>0:
        pos=pos+1
    elif i<0:
        neg+=1
    else:
        ceros=ceros+1
print(neg,pos,ceros)
        

0 7 2


In [41]:
def saludar(nombre):
    """
    Saluda a un usuario
    Args:
        nombre (str): Nombre de la persona a saludar
    Returns:
        str: Saludo personalizado
    """
    return f"¡Hola {nombre}! Bienvenido/a"

# Llamada a la función
print(saludar("Ana"))
print(saludar("Carlos"))

¡Hola Ana! Bienvenido/a
¡Hola Carlos! Bienvenido/a


In [ ]:
def calcular_iva(precio, iva=0.21):
    

In [42]:
def sumar_todo(*args):
    """Suma cualquier cantidad de números"""
    return sum(args)

print("Suma 3 números:", sumar_todo(5, 10, 15))
print("Suma 5 números:", sumar_todo(1, 2, 3, 4, 5))

Suma 3 números: 30
Suma 5 números: 15


In [ ]:
class Animal:
    def __init__(self, nombre):
        self.nombre = nombre
        
    def hablar(self):
        raise NotImplementedError("Método no implementado")

class Perro(Animal):
    def hablar(self):
        return f"¡{self.nombre} dice Guau!"

class Gato(Animal):
    def hablar(self):
        return f"¡{self.nombre} dice Miau!"

# Uso polimórfico
mascotas = [Perro("Buddy"), Gato("Luna")]
for mascota in mascotas:
    print(mascota.hablar())

In [46]:
pip3 install numpy


SyntaxError: invalid syntax (1773489910.py, line 1)

In [47]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [45]:
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a = np.array([2,3,5], dtype=float)

In [48]:
#Not a number NaN
a = np.array((np.nan, 5, 7))
print(a)

[nan  5.  7.]


In [50]:
a = np.array([
    [4,6,7,8],
    [6,3,4,5],
    [4,3,6,7]
])
print(a.shape)

(3, 4)


In [51]:
print(a.ndim)

2


In [52]:
print(a.size)


12


In [53]:
a = np.full((3,3),0)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [54]:
a = np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [55]:
a = np.ones((3,3), dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [56]:
a = np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


In [57]:
a = np.linspace(0,100,11)
print(a)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [59]:
a = np.array([2,3,4,5])
b = np.resize(a, (3, 3))
print(a)
print(b)

[2 3 4 5]
[[2 3 4]
 [5 2 3]
 [4 5 2]]


In [60]:
print(np.sqrt(9))

3.0


In [61]:
int(a.sum())

14

In [62]:
a = np.array([10, 20, 30])
b = np.array([20, 20, 10])
c = np.concatenate((a, b))
print(c)

[10 20 30 20 20 10]


In [65]:
a = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [1, 2, 3],
    [6, 7, 8]
])
print(np.split(a, 4))


[array([[4, 5, 6]]), array([[7, 8, 9]]), array([[1, 2, 3]]), array([[6, 7, 8]])]


In [ ]:

a = np.array([2, 5, 6, 7])
np.save('miarray.npy', a)
a = np.load('miarray.npy')


1. Genera un array que contenga 20 puntos espaciados uniformemente entre 0 y 5.

2. Dado un array arr = np.array([1, 2, 3, 4, 5]), calcula la suma, el promedio, el valor máximo y el valor mínimo.

3. 

In [66]:
puntos = np.linspace(0, 5, 20)
print(puntos)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [67]:
arr = np.array([1, 2, 3, 4, 5])
suma = np.sum(arr)
promedio = np.mean(arr)
maximo = np.max(arr)
minimo = np.min(arr)
print("Suma:", suma)
print("Promedio:", promedio)
print("Máximo:", maximo)
print("Mínimo:", minimo)

Suma: 15
Promedio: 3.0
Máximo: 5
Mínimo: 1



### 1. Organizar el horario de una conferencia
Estás organizando una conferencia y necesitas programar una serie de sesiones en una sala de reuniones. Dada una lista de duraciones de sesiones y un tiempo total disponible en horas, ¿cuántas sesiones caben dentro del tiempo disponible? Algunas sesiones pueden necesitar ser divididas en partes mas pequeáas.

- **Entrada**:
  - Una lista de duraciones de sesiones en minutos, por ejemplo `[30, 45, 60, 90, 15]`.
  - El tiempo total disponible en horas, por ejemplo `5 horas`.

- **Salida**:
  - Una lista de sesiones que pueden ser programadas dentro del tiempo disponible.


In [68]:
def programar_sesiones(duraciones, horas_disponibles):
    tiempo_disponible = horas_disponibles * 60  # pasar horas a minutos
    sesiones_programadas = []

    for sesion in duraciones:
        if tiempo_disponible > 0:
            if sesion <= tiempo_disponible:
                sesiones_programadas.append(sesion)
                tiempo_disponible -= sesion
            else:
                # añadir solo la parte que cabe
                sesiones_programadas.append(tiempo_disponible)
                tiempo_disponible = 0

    return sesiones_programadas


# Ejemplo
duraciones = [30, 45, 60, 90, 15]
horas_disponibles = 3

resultado = programar_sesiones(duraciones, horas_disponibles)
print("Sesiones programadas:", resultado)


Sesiones programadas: [30, 45, 60, 45]


In [69]:
def programar_sesiones_numpy(duraciones, horas_disponibles):
    duraciones = np.array(duraciones)
    tiempo_total = horas_disponibles * 60  # pasar a minutos

    # Suma acumulada de las sesiones
    acumulado = np.cumsum(duraciones)

    # Índices de sesiones que caben completas
    sesiones_completas = duraciones[acumulado <= tiempo_total]

    resultado = list(sesiones_completas)

    # Ver si queda tiempo para una sesión parcial
    if len(sesiones_completas) < len(duraciones):
        tiempo_usado = np.sum(sesiones_completas)
        tiempo_restante = tiempo_total - tiempo_usado
        
        if tiempo_restante > 0:
            resultado.append(tiempo_restante)

    return resultado


# Ejemplo
duraciones = [30, 45, 60, 90, 15]
horas_disponibles = 3

resultado = programar_sesiones_numpy(duraciones, horas_disponibles)
print("Sesiones programadas:", resultado)

Sesiones programadas: [30, 45, 60, 45]



### 7. Monitoreo de datos de salud
Se te han dado los datos de pasos diarios para un usuario. Tu tarea es:
- Calcular el número promedio de pasos por día.
- Encontrar el día con el mayor y menor número de pasos.
- Identificar los días en los que el usuario alcanza el objetivo de 10,000 pasos.

- **Entrada**:
  - Una lista de pasos diarios, por ejemplo `[8000, 12000, 9000, 15000, 11000, 10000, 8000, 7500, 10000]`.

- **Salida**:
  - El número promedio de pasos por día.
  - El día con el mayor y menor número de pasos.
  - La lista de días cuando el usuario alcanza el objetivo de 10,000 pasos.

In [70]:
pasos = np.array([8000, 12000, 9000, 15000, 11000, 10000, 8000, 7500, 10000])

# Promedio
promedio = np.mean(pasos)

# Máximo y mínimo
max_pasos = np.max(pasos)
min_pasos = np.min(pasos)

# Día del máximo y mínimo (+1 porque los días empiezan en 1)
dia_max = np.argmax(pasos) + 1
dia_min = np.argmin(pasos) + 1 #arg min() Indice

# Días con al menos 10,000 pasos
objetivo = 10000
dias_objetivo = np.where(pasos >= objetivo)[0] + 1

# Resultados
print("Promedio de pasos:", promedio)
print("Día con más pasos:", dia_max, f"({max_pasos} pasos)")
print("Día con menos pasos:", dia_min, f"({min_pasos} pasos)")
print("Días que alcanzan el objetivo:", dias_objetivo)

Promedio de pasos: 10055.555555555555
Día con más pasos: 4 (15000 pasos)
Día con menos pasos: 8 (7500 pasos)
Días que alcanzan el objetivo: [2 4 5 6 9]
